### ISSUE TITLE
Any benchmarks you can share for the GPU execution?

### ISSUE THREAD

**Issue by stoeckley** [athas/raytracinginoneweekendinfuthark#1]
I saw you posted a Futhark->C benchmark on Reddit, but how fast is this sample compared to C++ on CPU? Is it getting the desired GPU speedup for the rendering?

I'm fascinated by this language and what it's trying to do, and it almost feels too good to be true!

**Comment by athas** [comment]
Nothing is too good to be true, and Futhark has its warts.  The biggest one is that it's only really good in a specific domain (regular data parallelism), and while many interesting problems fit that domain, most people have not previously had reason to develop an intuition for what that domain is.

[While someone did write the equivalent ray tracer in CUDA C++](https://github.com/rogerallen/raytracinginoneweekendincuda), it crashes on my machines when I run it.  I wouldn't expect much difference in performance for this particular ray tracer, since it is so simple and brute force.  More complex ray tracers use tree-based acceleration structures that are (possibly?) amenable to more clever GPU implementation.  I don't know how Futhark would fare there.

**Comment by stoeckley** [comment]
I realize the algorithm itself is naive, but I'm not concerned about that; I'm more curious if you have any numbers how this Futhark sample performed on a particular GPU compared to the CPU?

Of course, what I should do is get started with this language and find out for myself! :)

**Comment by athas** [comment]
Oh, compared to C++ on the CPU?  That's easier.  On my CPU (Ryzen 1700X), the original C++ implementation compiled with -O3 takes 19.7s to render a 800x400 image with 10 samples per pixel. We can extrapolate that to 394s with 200 samples per pixel (compared to 4s for 200 samples per pixel on my Vega 64 GPU).  Futhark on the CPU is about the same.  Note that ray tracers like this are pretty trivial to parallelise, so the CPU code would probably run 32x faster if you parallelised it on a 32-core CPU.

Now, this is not the fastest possible C++ implementation of a ray tracer, but neither is the Futhark implementation unusually clever.  It's a straightforward translation done in a few hours, so I'm pretty satisfied with the performance.

**Comment by stoeckley** [comment]
I would agree that’s a pretty satisfying number. I actually have a C++ implementation from the same book, and on a laptop grade AMD GPU using Metal, it gets a factor of about 40X over a single CPU  core. You’re suggesting something more like 100X with your Vega, which is impressive considering the lack of overhead to writing the GPU code.
